import Foundation

extension LevelCatalog {
    static func seals(for number: Int) -> (control: SealKind, paradox: SealKind) {
        switch number {
        case 1: (.beforeEcho(3), .noDash)
        case 2: (.noDash, .parTime)
        case 3: (.maxEchoes(3), .parTime)
        case 4: (.useRift, .noShop)
        case 5: (.beforeEcho(4), .parTime)
        case 6: (.noDash, .maxEchoes(3))
        case 7: (.noShop, .parTime)
        case 8: (.maxEchoes(3), .noDash)
        case 9: (.parTime, .noShop)
        case 10: (.beforeEcho(4), .noDash)
        case 11: (.maxEchoes(3), .parTime)
        case 12: (.noShop, .avoidScar)
        case 13: (.useRift, .parTime)
        case 14: (.causeScar, .noShop)
        case 15: (.avoidScar, .parTime)
        case 16: (.useRift, .noDash)
        case 17: (.useRift, .parTime)
        case 18: (.causeScar, .noShop)
        case 19: (.noShop, .parTime)
        case 20: (.avoidScar, .noDash)
        case 21: (.maxEchoes(4), .parTime)
        case 22: (.noShop, .avoidScar)
        case 23: (.noDash, .parTime)
        case 24: (.avoidScar, .maxEchoes(4))
        case 25: (.causeScar, .parTime)
        case 26: (.noShop, .maxEchoes(4))
        case 27: (.avoidScar, .parTime)
        case 28: (.causeScar, .noDash)
        case 29: (.useRift, .noShop)
        case 30: (.noShop, .parTime)
        case 31: (.beforeEcho(4), .parTime)
        case 32: (.noDash, .avoidScar)
        case 33: (.maxEchoes(4), .noShop)
        case 34: (.useRift, .parTime)
        case 35: (.avoidScar, .noDash)
        case 36: (.noShop, .parTime)
        case 40: (.maxEchoes(3), .noShop)
        case 47: (.useRift, .parTime)
        case 61: (.noDash, .maxEchoes(3))
        case 68: (.useRift, .maxEchoes(4))
        default: (.parTime, .noDash)
        }
    }
}
